# Generated by Django 3.2 on 2021-06-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_subscribers_category_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscriber',
            new_name='subscribers',
        ),
    ]
